### ISSUE TITLE
Better external dep handling

### ISSUE THREAD

**Issue by nonword** [NYPL-discovery/discovery-api#58] opened 2017-07-14 13:59 UTC
We need to more gently handle 502s with certain remote dependencies. Presently when availability can't be checked, we get a 500. Should write tests against mocked responses (e.g. http://www.mocky.io/ ) to confirm we send the data we have even if we can't fold in availability, etc.

**Comment by kfriedman** [comment] 2017-07-14 14:21
FYI, this might be a duplicate of #22.

**Closed** 2017-07-14 14:21 UTC
